import { Review } from './types'

export const mockReviews: Review[] = [
  {
    id: 'rev-1',
    userName: 'Phạm Tiến Đạt',
    rating: 5,
    comment: 'Áo Nỉ chui đầu Lifewear mềm mại, giữ ấm tốt, thiết kế đơn giản dễ phối và thoải mái khi mặc.',
    size: 'M',
    color: 'Đen',
    tags: ['Sản phẩm đẹp', 'Giá tốt', 'Đóng gói đẹp', 'Giao hàng nhanh'],
    likes: 12,
    status: 'APPROVED',
    productId: 'p-1',
    productTitle: 'Áo Nỉ Chui Đầu Lifewear',
    productThumbnail: 'https://ik.imagekit.io/htnacim0q/media-ak-shop/product-photo_2025-09-13_09-01-01_cuhynT4qY',
    createdAt: '2025-12-01T10:00:00Z',
    replies: [
      {
        id: 'rep-1',
        adminName: 'Admin',
        content: 'Cảm ơn bạn đã ủng hộ shop nhé!',
        createdAt: '2025-12-01T11:00:00Z',
      }
    ]
  },
  {
    id: 'rev-2',
    userName: 'Chu Văn Thái',
    rating: 4,
    comment: 'Form áo hơi rộng so với mình nhưng chất nỉ rất thích, mặc mùa đông thì tuyệt vời.',
    size: 'L',
    color: 'Xám',
    tags: ['Chất lượng cao', 'Giao hàng nhanh'],
    likes: 5,
    status: 'PENDING',
    productId: 'p-2',
    productTitle: 'Áo Hoodie Form Rộng',
    productThumbnail: 'https://ik.imagekit.io/htnacim0q/media-ak-shop/product-photo_2025-09-13_09-01-01_NXOzAa321',
    createdAt: '2025-11-13T14:30:00Z',
  },
  {
    id: 'rev-3',
    userName: 'Nguyễn Văn An',
    rating: 5,
    comment: 'Sản phẩm rất tốt, đúng như mô tả. Sẽ tiếp tục ủng hộ shop.',
    size: 'XL',
    color: 'Trắng',
    tags: ['Sản phẩm đẹp', 'Giao hàng nhanh'],
    likes: 8,
    status: 'APPROVED',
    productId: 'p-3',
    productTitle: 'Áo Thun Cotton Basic',
    productThumbnail: 'https://ik.imagekit.io/htnacim0q/media-ak-shop/product-photo_2025-09-13_09-01-01_VFy_9gwkE',
    createdAt: '2025-12-05T09:15:00Z',
  },
  {
    id: 'rev-4',
    userName: 'Lê Thị Bình',
    rating: 3,
    comment: 'Vải hơi mỏng so với mong đợi, nhưng kiểu dáng thì đẹp.',
    size: 'S',
    color: 'Hồng',
    tags: ['Giá tốt'],
    likes: 2,
    status: 'HIDDEN',
    productId: 'p-4',
    productTitle: 'Áo Khoác Gió Nữ',
    productThumbnail: 'https://ik.imagekit.io/htnacim0q/media-ak-shop/product-photo_2025-09-13_09-01-01_cuhynT4qY',
    createdAt: '2025-12-10T16:45:00Z',
  },
  {
    id: 'rev-5',
    userName: 'Trần Minh Tâm',
    rating: 5,
    comment: 'Giao hàng cực nhanh, đóng gói cẩn thận. Rất hài lòng.',
    size: 'M',
    color: 'Xanh',
    tags: ['Giao hàng nhanh', 'Đóng gói đẹp'],
    likes: 15,
    status: 'PENDING',
    productId: 'p-5',
    productTitle: 'Quần Jean Slim Fit',
    productThumbnail: 'https://ik.imagekit.io/htnacim0q/media-ak-shop/product-photo_2025-09-13_09-01-01_NXOzAa321',
    createdAt: '2025-12-12T08:20:00Z',
  }
]
